application: ambitvpgen
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /(.+)
  static_files: web/\1
  upload: web/(.+)

- url: /
  static_files: web/index.html
  upload: web/index.html
